### ISSUE TITLE
 UI revamping

### ISSUE THREAD

**Issue by GNUuser** [koso00/depecher#4]
I think the Depecher interface doesn't look very good and needs a redesign. Some screenshots of the Sailorgram 0.9 design that was never released but that for me has a very nice interface, which we can reuse for Depecher. 

![Captura_20200606_002](https://user-images.githubusercontent.com/45316884/84555021-c07c8e80-ace8-11ea-8adf-c9241ecab523.png)

![Captura_20200606_001](https://user-images.githubusercontent.com/45316884/84555008-b2c70900-ace8-11ea-83ce-6874e67fd561.png)

**Comment by GNUuser** [comment]
@koso00 I've been thinking a lot that maybe it would have been better forking Sailorgram 0.9 this has advantages of the graphical interface compared to Depecher.

**Comment by koso00** [comment]
i'm working a bit less on depecher because of my main work, anyway i used
depecher as a base because it's more reliable

Il giorno dom 12 lug 2020 alle ore 17:30 carlosgonz <
notifications@github.com> ha scritto:
